spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
hystrix:    
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000      
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000    
#自定义负载均衡策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
 
management:
  endpoints:
    web:
      exposure:
        include: "*"        
